name: Supabase Keep-Alive Ping

on:
  schedule:
    # runs every day at 02:00 UTC — adjust as needed
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Supabase keep-alive endpoint
        run: |
          curl -fsS https://arncxalleyggoqzdvgnh.supabase.co/rest/v1/seasense_raw?select=* || exit 1
